<?php

namespace Database\Seeders;

use App\Models\Report;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ReportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $reports = [
            [
                'title' => 'Laporan Kemajuan Pembangunan Jalan Raya Penghubung Desa',
                'files' => json_encode(['images/bg-kegiatan-1.png', 'images/bg-kegiatan-2.png', 'images/bg-kegiatan-3.png']),
                'description' => 'Laporan ini mencakup kemajuan pembangunan jalan raya sepanjang 5 km dari total 10 km yang direncanakan. Termasuk analisis tantangan dan solusi yang diterapkan.',
                'funds' => 5000000000,
                'status' => 'diterima',
                'realization_date' => now()->subDays(30),
                'project_id' => 1,
                'partner_id' => 4,
                'is_submitted' => true,
            ],
            [
                'title' => 'Evaluasi Tengah Tahun Pembangunan Laboratorium IPA',
                'files' => json_encode(['images/bg-kegiatan-3.png', 'images/bg-kegiatan-4.png']),
                'description' => 'Laporan evaluasi tengah tahun untuk proyek pembangunan laboratorium IPA di SMA Negeri 1 Astanajapura. Mencakup penilaian kualitas bangunan dan peralatan yang telah dipasang.',
                'funds' => 750000000,
                'status' => 'draf',
                'realization_date' => now()->subDays(15),
                'project_id' => 2,
                'partner_id' => 2,
                'is_submitted' => false,
            ],
            [
                'title' => 'Laporan Akhir Renovasi Puskesmas Babakan',
                'files' => json_encode(['images/bg-kegiatan-2.png', 'images/bg-kegiatan-3.png', 'images/bg-kegiatan-4.png']),
                'description' => 'Laporan akhir proyek renovasi dan peningkatan fasilitas Puskesmas Babakan. Termasuk dokumentasi fasilitas baru dan peningkatan layanan yang dapat diberikan.',
                'funds' => 2000000000,
                'status' => 'diterima',
                'realization_date' => now()->subDays(7),
                'project_id' => 3,
                'partner_id' => 3,
                'is_submitted' => true,
            ],
            [
                'title' => 'Progres Pembangunan Taman Kota Hijau Beber',
                'files' => json_encode(['images/bg-kegiatan-1.png', 'images/bg-kegiatan-4.png']),
                'description' => 'Laporan kemajuan pembangunan taman kota hijau di Beber. Mencakup perkembangan penanaman pohon dan pembangunan fasilitas rekreasi.',
                'funds' => 3000000000,
                'status' => 'draf',
                'realization_date' => now()->subDays(10),
                'project_id' => 4,
                'partner_id' => 5,
                'is_submitted' => false,
            ],
            [
                'title' => 'Laporan Tahap Awal Revitalisasi Pasar Tradisional Ciledug',
                'files' => json_encode(['images/bg-kegiatan-4.png', 'images/bg-kegiatan-2.png']),
                'description' => 'Laporan tahap awal proyek revitalisasi pasar tradisional di Ciledug. Termasuk survei kondisi existing dan rencana detail revitalisasi.',
                'funds' => 1500000000,
                'status' => 'draf',
                'realization_date' => now()->subDays(20),
                'project_id' => 5,
                'partner_id' => 1,
                'is_submitted' => false,
            ],
            [
                'title' => 'Evaluasi Dampak Pembangunan Jalan Raya terhadap Ekonomi Lokal',
                'files' => json_encode(['images/bg-kegiatan-3.png', 'images/bg-kegiatan-2.png']),
                'description' => 'Laporan evaluasi dampak pembangunan jalan raya penghubung desa terhadap perekonomian lokal. Mencakup analisis peningkatan mobilitas dan akses pasar.',
                'funds' => 200000000,
                'status' => 'diterima',
                'realization_date' => now()->subDays(5),
                'project_id' => 1,
                'partner_id' => 6,
                'is_submitted' => true,
            ],
            [
                'title' => 'Laporan Pengadaan Peralatan Laboratorium IPA',
                'files' => json_encode(['images/bg-kegiatan-1.png', 'images/bg-kegiatan-4.png', 'images/bg-kegiatan-3.png']),
                'description' => 'Laporan rinci mengenai pengadaan dan instalasi peralatan untuk laboratorium IPA di SMA Negeri 1 Astanajapura. Termasuk daftar inventaris dan panduan penggunaan.',
                'funds' => 1000000000,
                'status' => 'revisi',
                'realization_date' => now()->subDays(12),
                'project_id' => 2,
                'partner_id' => 7,
                'is_submitted' => true,
            ],
            [
                'title' => 'Analisis Peningkatan Layanan Kesehatan Puskesmas Babakan',
                'files' => json_encode(['images/bg-kegiatan-2.png', 'images/bg-kegiatan-3.png']),
                'description' => 'Laporan analisis peningkatan kualitas dan kuantitas layanan kesehatan di Puskesmas Babakan pasca renovasi. Termasuk data statistik kunjungan pasien dan kepuasan masyarakat.',
                'funds' => 300000000,
                'status' => 'revisi',
                'realization_date' => now()->subDays(3),
                'project_id' => 3,
                'partner_id' => 3,
                'is_submitted' => true,
            ],
            [
                'title' => 'Laporan Penanaman Pohon dan Vegetasi di Taman Kota Beber',
                'files' => json_encode(['images/bg-kegiatan-4.png', 'images/bg-kegiatan-3.png', 'images/bg-kegiatan-2.png']),
                'description' => 'Laporan detail mengenai jenis dan jumlah pohon serta vegetasi yang ditanam di Taman Kota Hijau Beber. Termasuk rencana perawatan dan pemeliharaan jangka panjang.',
                'funds' => 500000000,
                'status' => 'diterima',
                'realization_date' => now()->subDays(8),
                'project_id' => 4,
                'partner_id' => 5,
                'is_submitted' => true,
            ],
            [
                'title' => 'Progres Renovasi Kios dan Fasilitas Pasar Tradisional Ciledug',
                'files' => json_encode(['images/bg-kegiatan-1.png', 'images/bg-kegiatan-2.png']),
                'description' => 'Laporan kemajuan renovasi kios pedagang dan fasilitas umum di Pasar Tradisional Ciledug. Mencakup perbaikan sistem drainase dan pengelolaan sampah.',
                'funds' => 2500000000,
                'status' => 'revisi',
                'realization_date' => now()->subDays(2),
                'project_id' => 5,
                'partner_id' => 4,
                'is_submitted' => true,
            ],
            [
                'title' => 'Laporan Progres Pembangunan Jembatan',
                'files' => json_encode(['images/bg-kegiatan-4.png']),
                'description' => 'Laporan mengenai progres pembangunan jembatan yang menghubungkan dua desa.',
                'funds' => 4000000000,
                'status' => 'diterima',
                'realization_date' => '2023-01-15',
                'project_id' => 1,
                'partner_id' => 2,
                'is_submitted' => true,
            ],
            [
                'title' => 'Laporan Akhir Proyek Pembangunan Sekolah',
                'files' => json_encode(['images/bg-kegiatan-1.png']),
                'description' => 'Laporan akhir proyek pembangunan sekolah dasar di desa.',
                'funds' => 3000000000,
                'status' => 'diterima',
                'realization_date' => '2023-04-20',
                'project_id' => 2,
                'partner_id' => 5,
                'is_submitted' => true,
            ],
            [
                'title' => 'Evaluasi Proyek Pembangunan Jalan Desa',
                'files' => json_encode(['images/bg-kegiatan-2.png']),
                'description' => 'Laporan evaluasi proyek pembangunan jalan desa yang baru selesai.',
                'funds' => 2000000000,
                'status' => 'draf',
                'realization_date' => '2023-07-10',
                'project_id' => 3,
                'partner_id' => 6,
                'is_submitted' => false,
            ],
            [
                'title' => 'Laporan Pembangunan Fasilitas Olahraga',
                'files' => json_encode(['images/bg-kegiatan-3.png']),
                'description' => 'Laporan mengenai pembangunan fasilitas olahraga di kota.',
                'funds' => 1500000000,
                'status' => 'diterima',
                'realization_date' => '2023-10-05',
                'project_id' => 4,
                'partner_id' => 1,
                'is_submitted' => true,
            ],
            [
                'title' => 'Laporan Progres Pembangunan Taman Kota',
                'files' => json_encode(['images/bg-kegiatan-4.png']),
                'description' => 'Laporan progres pembangunan taman kota yang baru.',
                'funds' => 1000000000,
                'status' => 'draf',
                'realization_date' => '2023-11-15',
                'project_id' => 5,
                'partner_id' => 4,
                'is_submitted' => false,
            ],
            [
                'title' => 'Laporan Pengadaan Alat Kesehatan',
                'files' => json_encode(['images/bg-kegiatan-1.png']),
                'description' => 'Laporan pengadaan alat kesehatan untuk puskesmas.',
                'funds' => 500000000,
                'status' => 'diterima',
                'realization_date' => now()->subDays(1),
                'project_id' => 1,
                'partner_id' => 2,
                'is_submitted' => true,
            ],
            [
                'title' => 'Laporan Pembangunan Jaringan Air Bersih',
                'files' => json_encode(['images/bg-kegiatan-2.png']),
                'description' => 'Laporan pembangunan jaringan air bersih di desa.',
                'funds' => 2500000000,
                'status' => 'revisi',
                'realization_date' => now()->subDays(5),
                'project_id' => 2,
                'partner_id' => 3,
                'is_submitted' => true,
            ],
            [
                'title' => 'Laporan Pemeliharaan Jalan',
                'files' => json_encode(['images/bg-kegiatan-3.png']),
                'description' => 'Laporan pemeliharaan jalan yang telah dilakukan.',
                'funds' => 800000000,
                'status' => 'diterima',
                'realization_date' => now()->subDays(10),
                'project_id' => 3,
                'partner_id' => 6,
                'is_submitted' => false,
            ],
            [
                'title' => 'Laporan Pembangunan Pusat Kesehatan',
                'files' => json_encode(['images/bg-kegiatan-4.png']),
                'description' => 'Laporan pembangunan pusat kesehatan di daerah terpencil.',
                'funds' => 6000000000,
                'status' => 'draf',
                'realization_date' => now()->subDays(15),
                'project_id' => 4,
                'partner_id' => 7,
                'is_submitted' => true,
            ],
            [
                'title' => 'Laporan Revitalisasi Ruang Publik',
                'files' => json_encode(['images/bg-kegiatan-1.png']),
                'description' => 'Laporan revitalisasi ruang publik untuk masyarakat.',
                'funds' => 3500000000,
                'status' => 'revisi',
                'realization_date' => now()->subDays(20),
                'project_id' => 5,
                'partner_id' => 5,
                'is_submitted' => true,
            ],
        ];

        Report::insert($reports);
    }
}
