name: Deploy Laravel to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 'latest' 

    - name: Run deployment script via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          cd /var/www/csr-smkdev-league
          sudo -u www-data git pull origin main
          sudo -u www-data composer install --no-interaction --prefer-dist --optimize-autoloader
          BUN=$(which bun)
          $BUN install
          $BUN run build
          sudo -u www-data php artisan optimize
          sudo service nginx restart
